### ISSUE TITLE
Android studio. Rendering problems in preview

### ISSUE THREAD

**Issue by ZBlaZe** [castorflex/SmoothProgressBar#41]
![cars mall - eprojectsandroidcarsmallproject - app - appsrcmainreslayoutactivity_splash_screen xml - android studio beta 0 8 6 jpg](https://cloud.githubusercontent.com/assets/7900439/3911733/4428e328-2324-11e4-8553-54b86e76bd90.jpg)

**Comment by mradzinski** [comment]
+1, and everyone using the latest version of the library has exactly the same issue.

**Comment by eeVoskos** [comment]
+1

**Comment by Mithrandir21** [comment]
This seems to be a reoccurrence of issue #30.
I thought this was fixed by adding the "isInEditMode" fix.
What happened?

**Comment by castorflex** [comment]
I just uploaded a snapshot that should fix the problem. Can you confirm that it's ok for you before I push it on maven central? 
You will just add the following to use the snapshots

```gradle
repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
dependencies {
    compile 'com.github.castorflex.smoothprogressbar:library:1.1.0-SNAPSHOT@aar'
}
```

**Comment by Mithrandir21** [comment]
Just added the the lines needed, did "Clean project" and "Rebuild project".
I'm not getting the same error as before and there is a (Android Standard) progress bar shown in the preview, but now there seems to be a message about a missing color.

This is the View I have tried to add (also tried with the first example in the readme page, but got the same result):

```
<fr.castorflex.android.smoothprogressbar.SmoothProgressBar
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
```


Here is the top part of the error message in the Preview page:
```
Missing styles. Is the correct theme chosen for this layout?  Use the Theme combo box above the layout to choose a different layout, or fix the theme style references. 

The following classes could not be instantiated:
- fr.castorflex.android.smoothprogressbar.SmoothProgressBar (Open Class, Show Exception)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE  

Exception Details
java.lang.NullPointerException
	at android.content.res.BridgeResources.getColor(BridgeResources.java:182)
	at fr.castorflex.android.smoothprogressbar.SmoothProgressDrawable$Builder.initValues(SmoothProgressDrawable.java:672)
	at fr.castorflex.android.smoothprogressbar.SmoothProgressDrawable$Builder.<init>(SmoothProgressDrawable.java:633)
	at fr.castorflex.android.smoothprogressbar.SmoothProgressBar.<init>(SmoothProgressBar.java:38)
	at fr.castorflex.android.smoothprogressbar.SmoothProgressBar.<init>(SmoothProgressBar.java:31)
	at sun.reflect.GeneratedConstructorAccessor632.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:413)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
	at com.android.tools.idea.rendering.LayoutlibCallback.loadView(LayoutlibCallback.java:176)
    .....
```


Maybe I'm doing something wrong. Let me know if you need me to test anything else.

**Comment by castorflex** [comment]
I've juste re-upload a 1.1.0-SNAPSHOT version, it should be ok now. You will likely need to clear your local maven cache before.
